{% set name = "znsocket" %}
{% set version = "0.2.8" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/znsocket-{{ version }}.tar.gz
  sha256: e2190928775414fdd426dc342c1cc2464eb449e6a669b256c54876c94ea1163b

build:
  entry_points:
    - znsocket = znsocket.cli:app
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }},<4.0.0
    - python-socketio >=5.12.1
    - eventlet >=0.39.0
    - typer >=0.13
    - znjson >=0.2.6
    - redis-py >=5.2.1

test:
  imports:
    - znsocket
  commands:
    - pip check
    - znsocket --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/zincware/ZnSocket
  summary: Python implementation of a Redis-compatible API using websockets.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
